### ISSUE TITLE
RoadMap reader crashes with Out of memory

### ISSUE THREAD

**Issue by sergyv** [bmwcarit/barefoot#10]
Hello,

i just tried to use a bigger map - the whole Germany. Import procedure finishes succesfully, but when I start the server and it begins importing data from Postgres after about 5000000 ways it crashes with java.lang.OutOfmemoryError java heap space error.
I tried increasing memory size for the heap, but then it crashes with GC overhead limit exceeded.

have you tried working with bigger maps? any suggestions on how to solve this problem?

thanks!

```
2016-05-21 21:58:46,025 INFO  [main] RoadMap: inserted 5000000 (9292848) roads
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredField(Class.java:2068)
        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl$1.run(AtomicReferenceFieldUpdater.java:316)
        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl$1.run(AtomicReferenceFieldUpdater.java:314)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:313)
        at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:109)
        at java.sql.SQLException.<clinit>(SQLException.java:372)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1857)
        at org.postgresql.core.v3.QueryExecutorImpl.fetch(QueryExecutorImpl.java:2089)
        at org.postgresql.jdbc2.AbstractJdbc2ResultSet.next(AbstractJdbc2ResultSet.java:1916)
        at com.bmwcarit.barefoot.road.PostGISReader.next(PostGISReader.java:140)
        at com.bmwcarit.barefoot.roadmap.RoadMap.Load(RoadMap.java:140)
        at com.bmwcarit.barefoot.matcher.ServerControl.initServer(ServerControl.java:116)
        at com.bmwcarit.barefoot.matcher.ServerControl.main(ServerControl.java:245)
2016-05-21 23:40:49,980 INFO  [Thread-0] ServerControl: stopping server
2016-05-21 23:40:49,982 ERROR [Thread-0] ServerControl: stopping server failed, not yet started
```

**Comment by smattheis** [comment]
I've imported for example europe map on server-like machines with 32GB of memory. What's the memory size of your machine? How did you increase the heap size?

**Comment by sergyv** [comment]
Sebastian, there is 16Gb on the server, I just tried to increase heap size to 8Gb with -Xmx8G and it worked out fine, sorry for bothering.
Good to know 32Gb is enough for Europe;)

**Comment by smattheis** [comment]
No problem, you're very welcome. Don't hesitate to create an issue if you have any trouble.
