### ISSUE TITLE
Issue downloading gradle during installation.

### ISSUE THREAD

**Issue by verfum** [bmwcarit/barefoot#147]
Hi, I am having an issue building docker on Windows desktop. It fails downloading http://services.gradle.org/distributions/gradle-1.4-bin.zip
I can download this using chrome. I have also tried building on different machines with different internet connection with no firewall enabled.
Is this an issue with docker/barefoot/firewall?

This is the output I get from the build:

C:\mapmatching\barefoot>docker build -t barefoot-map ./map
Sending build context to Docker daemon  178.7MB
Step 1/7 : FROM ubuntu:14.04
 ---> 6e4f1fe62ff1
Step 2/7 : MAINTAINER sebastian.mattheis@bmw-carit.de
 ---> Using cache
 ---> 8ed9eca9c38e
Step 3/7 : ADD /pgsql/ /opt/pgsql/
 ---> Using cache
 ---> 2d10d4e0f19c
Step 4/7 : RUN apt-get update && apt-get -y install patch postgresql-9.3-postgis-2.1 git openjdk-7-jdk python-psycopg2 python-numpy python-gdal
 ---> Using cache
 ---> fdd3a88a6098
Step 5/7 : RUN patch /etc/postgresql/9.3/main/postgresql.conf < /opt/pgsql/postgresql.conf.patch && patch /etc/postgresql/9.3/main/pg_hba.conf < /opt/pgsql/pg_hba.conf.patch && echo "export HOME=/root" >> /root/.bashrc
 ---> Using cache
 ---> 6b5875dc9e4f
Step 6/7 : RUN cd /opt/ && git clone https://github.com/openstreetmap/osmosis.git && cd osmosis && git checkout tags/0.43.1 && ./gradlew assemble && echo "export PATH=${PATH}:/opt/osmosis/package/bin" >> /root/.bashrc
 ---> Running in bc1b9af1c698
Cloning into 'osmosis'...
Note: checking out 'tags/0.43.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at ad5c5bd... Remove RELEASE version number suffix from release builds
Downloading http://services.gradle.org/distributions/gradle-1.4-bin.zip

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-1.4-bin.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1694)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:63)
        at org.gradle.wrapper.Download.download(Download.java:49)
        at org.gradle.wrapper.Install.createDist(Install.java:51)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
The command '/bin/sh -c cd /opt/ && git clone https://github.com/openstreetmap/osmosis.git && cd osmosis && git checkout tags/0.43.1 && ./gradlew assemble && echo "export PATH=${PATH}:/opt/osmosis/package/bin" >> /root/.bashrc' returned a non-zero code: 1

**Comment by morningstarwang** [comment]
@verfum it can't be downloaded using chrome either now...

**Comment by pabloito** [comment]
The Issue seems to be the link is missing an https://

http://services.gradle.org/distributions/gradle-1.4-bin.zip Does not Work
https://services.gradle.org/distributions/gradle-1.4-bin.zip Does work.

It would be nice if they patched this.
