### ISSUE TITLE
JSON request faulty or incomplete

### ISSUE THREAD

**Issue by eufr** [bmwcarit/barefoot#33]
Thanks again for this awesome library and sorry for bothering again.

I'm experiencing a weird issue. I managed to start a matcher server and successfully retrieve some matching points for a set of given GPS coordinates. However, after restarting the matcher server and submitting **the same sample data again**, the matcher server returns the following error:

```
2016-10-12 13:37:46,841 ERROR [pool-2-thread-24] TrackerServer: JSON request faulty or incomplete: {"format": "geojson", "request": [{"time": "2014-09-10 06:54:07+0200", "id": "\\x0001", "point": "POINT(9.39050628 47.43421293)"}, {"time": "2014-09-10 06:54:22+0200", "id": "\\x0001", "point": "POINT(9.39047829 47.43405053)"}, {"time": "2014-09-10 06:54:37+0200", "id": "\\x0001", "point": "POINT(9.39040549 47.43400307)"}, {"time": "2014-09-10 06:54:52+0200", "id": "\\x0001", "point": "POINT(9.39048218 47.4339819)"}, {"time": "2014-09-10 06:55:07+0200", "id": "\\x0001", "point": "POINT(9.39050034 47.43392939)"}, {"time": "2014-09-10 06:55:22+0200", "id": "\\x0001", "point": "POINT(9.39052741 47.43386315)"}, {"time": "2014-09-10 06:55:37+0200", "id": "\\x0001", "point": "POINT(9.39053714 47.43379712)"}, {"time": "2014-09-10 06:55:52+0200", "id": "\\x0001", "point": "POINT(9.39056102 47.43372544)"}, {"time": "2014-09-10 06:56:07+0200", "id": "\\x0001", "point": "POINT(9.39057812 47.43367572)"}, {"time": "2014-09-10 06:56:22+0200", "id": "\\x0001", "point": "POINT(9.39060296 47.43362181)"}, {"time": "2014-09-10 06:56:37+0200", "id": "\\x0001", "point": "POINT(9.39062649 47.43357349)"}, {"time": "2014-09-10 06:56:52+0200", "id": "\\x0001", "point": "POINT(9.39064449 47.43352041)"}, {"time": "2014-09-10 06:57:07+0200", "id": "\\x0001", "point": "POINT(9.39066988 47.43347638)"}, {"time": "2014-09-10 06:57:22+0200", "id": "\\x0001", "point": "POINT(9.39069002 47.43341559)"}, {"time": "2014-09-10 06:57:37+0200", "id": "\\x0001", "point": "POINT(9.39072274 47.43335014)"}, {"time": "2014-09-10 06:57:52+0200", "id": "\\x0001", "point": "POINT(9.3907569 47.43329393)"}, {"time": "2014-09-10 06:58:07+0200", "id": "\\x0001", "point": "POINT(9.3907865 47.43323207)"}, {"time": "2014-09-10 06:58:22+0200", "id": "\\x0001", "point": "POINT(9.39078946 47.43317082)"}, {"time": "2014-09-10 06:58:37+0200", "id": "\\x0001", "point": "POINT(9.39082222 47.43313115)"}]}
java.lang.RuntimeException: JSON request faulty or incomplete: {"format": "geojson", "request": [{"time": "2014-09-10 06:54:07+0200", "id": "\\x0001", "point": "POINT(9.39050628 47.43421293)"}, {"time": "2014-09-10 06:54:22+0200", "id": "\\x0001", "point": "POINT(9.39047829 47.43405053)"}, {"time": "2014-09-10 06:54:37+0200", "id": "\\x0001", "point": "POINT(9.39040549 47.43400307)"}, {"time": "2014-09-10 06:54:52+0200", "id": "\\x0001", "point": "POINT(9.39048218 47.4339819)"}, {"time": "2014-09-10 06:55:07+0200", "id": "\\x0001", "point": "POINT(9.39050034 47.43392939)"}, {"time": "2014-09-10 06:55:22+0200", "id": "\\x0001", "point": "POINT(9.39052741 47.43386315)"}, {"time": "2014-09-10 06:55:37+0200", "id": "\\x0001", "point": "POINT(9.39053714 47.43379712)"}, {"time": "2014-09-10 06:55:52+0200", "id": "\\x0001", "point": "POINT(9.39056102 47.43372544)"}, {"time": "2014-09-10 06:56:07+0200", "id": "\\x0001", "point": "POINT(9.39057812 47.43367572)"}, {"time": "2014-09-10 06:56:22+0200", "id": "\\x0001", "point": "POINT(9.39060296 47.43362181)"}, {"time": "2014-09-10 06:56:37+0200", "id": "\\x0001", "point": "POINT(9.39062649 47.43357349)"}, {"time": "2014-09-10 06:56:52+0200", "id": "\\x0001", "point": "POINT(9.39064449 47.43352041)"}, {"time": "2014-09-10 06:57:07+0200", "id": "\\x0001", "point": "POINT(9.39066988 47.43347638)"}, {"time": "2014-09-10 06:57:22+0200", "id": "\\x0001", "point": "POINT(9.39069002 47.43341559)"}, {"time": "2014-09-10 06:57:37+0200", "id": "\\x0001", "point": "POINT(9.39072274 47.43335014)"}, {"time": "2014-09-10 06:57:52+0200", "id": "\\x0001", "point": "POINT(9.3907569 47.43329393)"}, {"time": "2014-09-10 06:58:07+0200", "id": "\\x0001", "point": "POINT(9.3907865 47.43323207)"}, {"time": "2014-09-10 06:58:22+0200", "id": "\\x0001", "point": "POINT(9.39078946 47.43317082)"}, {"time": "2014-09-10 06:58:37+0200", "id": "\\x0001", "point": "POINT(9.39082222 47.43313115)"}]}
	at com.bmwcarit.barefoot.tracker.TrackerServer$MatcherResponseFactory$2.response(TrackerServer.java:246)
	at com.bmwcarit.barefoot.util.AbstractServer$ResponseHandler.call(AbstractServer.java:143)
	at com.bmwcarit.barefoot.util.AbstractServer$ResponseHandler.call(AbstractServer.java:119)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I ran the following command:

```
root@f1cc0014739b:/mnt# python util/submit/batch.py --host localhost --port 1234  --file src/test/resources/com/bmwcarit/barefoot/matcher/sample.json
```

Here's the content of sample.json:
```
[{"point":"POINT(9.39050628 47.43421293)","time":"2014-09-10 06:54:07+0200","id":"\\x0001"},{"point":"POINT(9.39047829 47.43405053)","time":"2014-09-10 06:54:22+0200","id":"\\x0001"},{"point":"POINT(9.39040549 47.43400307)","time":"2014-09-10 06:54:37+0200","id":"\\x0001"},{"point":"POINT(9.39048218 47.4339819)","time":"2014-09-10 06:54:52+0200","id":"\\x0001"},{"point":"POINT(9.39050034 47.43392939)","time":"2014-09-10 06:55:07+0200","id":"\\x0001"},{"point":"POINT(9.39052741 47.43386315)","time":"2014-09-10 06:55:22+0200","id":"\\x0001"},{"point":"POINT(9.39053714 47.43379712)","time":"2014-09-10 06:55:37+0200","id":"\\x0001"},{"point":"POINT(9.39056102 47.43372544)","time":"2014-09-10 06:55:52+0200","id":"\\x0001"},{"point":"POINT(9.39057812 47.43367572)","time":"2014-09-10 06:56:07+0200","id":"\\x0001"},{"point":"POINT(9.39060296 47.43362181)","time":"2014-09-10 06:56:22+0200","id":"\\x0001"},{"point":"POINT(9.39062649 47.43357349)","time":"2014-09-10 06:56:37+0200","id":"\\x0001"},{"point":"POINT(9.39064449 47.43352041)","time":"2014-09-10 06:56:52+0200","id":"\\x0001"},{"point":"POINT(9.39066988 47.43347638)","time":"2014-09-10 06:57:07+0200","id":"\\x0001"},{"point":"POINT(9.39069002 47.43341559)","time":"2014-09-10 06:57:22+0200","id":"\\x0001"},{"point":"POINT(9.39072274 47.43335014)","time":"2014-09-10 06:57:37+0200","id":"\\x0001"},{"point":"POINT(9.3907569 47.43329393)","time":"2014-09-10 06:57:52+0200","id":"\\x0001"},{"point":"POINT(9.3907865 47.43323207)","time":"2014-09-10 06:58:07+0200","id":"\\x0001"},{"point":"POINT(9.39078946 47.43317082)","time":"2014-09-10 06:58:22+0200","id":"\\x0001"},{"point":"POINT(9.39082222 47.43313115)","time":"2014-09-10 06:58:37+0200","id":"\\x0001"}]
```

Can you think of any reason why the matcher server does not accept my sample.json file anymore? It seems as if there's something wrong with my json file, but then again why was it successful in the first run? Restarting the matcher server did not help. The matcher server does not accept any json file anymore.

Thanks for your help!

**Comment by smattheis** [comment]
Are you running the tracker or the matcher server? (These servers are independent from each other for historic reasons, and expect different input types: matcher - array of samples, tracker - samples one after the other.) The log indicates that you're running the tracker, but you send an array of samples which is the expected input of the matcher.

**Comment by eufr** [comment]
Oh yes, you're right. I must have mixed it up. Now it's working like a charm. Thanks again for the great support!
