### ISSUE TITLE
Matcher server Opening PostgreSQL connection failed

### ISSUE THREAD

**Issue by rahimramezanian** [bmwcarit/barefoot#44]
I followed the Matcher server part. In step 3 I got the following error. 

```
$ java -jar target/barefoot-0.1.0-matcher-jar-with-dependencies.jar --geojson config/server.properties config/oberbayern.properties
2017-02-08 15:34:18,022 INFO  [main] ServerControl: initialize server
2017-02-08 15:34:18,027 INFO  [main] ServerControl: read database properties from file config/oberbayern.properties
2017-02-08 15:34:18,029 INFO  [main] Loader: load map from database oberbayern
2017-02-08 15:34:18,029 INFO  [main] Loader: open road reader for database oberbayern at localhost:5432
2017-02-08 15:34:18,029 INFO  [main] Loader: database.host=localhost
2017-02-08 15:34:18,030 INFO  [main] Loader: database.port=5432
2017-02-08 15:34:18,030 INFO  [main] Loader: database.name=oberbayern
2017-02-08 15:34:18,030 INFO  [main] Loader: database.table=bfmap_ways
2017-02-08 15:34:18,030 INFO  [main] Loader: database.user=osmuser
2017-02-08 15:34:18,030 INFO  [main] Loader: database.road-types=./map/tools/road-types.json
2017-02-08 15:34:18,065 INFO  [main] PostGISReader: open reader (standard)
2017-02-08 15:34:18,065 INFO  [main] PostGISReader: open reader (parameterized)
2017-02-08 15:36:25,268 ERROR [main] ServerControl: Opening PostgreSQL connection failed: The connection attempt failed.
2017-02-08 15:36:25,269 INFO  [Thread-0] ServerControl: stopping server
2017-02-08 15:36:25,270 ERROR [Thread-0] ServerControl: stopping server failed, not yet started
```

Thanks for your helps.

**Comment by smattheis** [comment]
What does a `sudo docker ps -a` say?

**Comment by rahimramezanian** [comment]
Hi.
It says

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
3b09b8ecf295        barefoot-map        "/bin/sh -c 'servi..."   29 minutes ago      Up 28 minutes       0.0.0.0:5432->5432/tcp   barefoot
```

and execution of 
```
bash /mnt/map/osm/import.sh
```
in docker is done
```
root@3b09b8ecf295:/# bash /mnt/map/osm/import.sh
Start creation and initialization of database 'oberbayern' ...
.
.
.
590588 segments from 556462 ways inserted.
590588 segments from 556462 ways inserted and finished.
Done.
Done.
```

Thanks.

**Comment by smattheis** [comment]
What's your setup: What's your host operating system? Are the matcher server and the map server started on the same machine? Do you use the default oberbayern.properties configuration?

**Comment by rahimramezanian** [comment]
_What's your host operating system?_ **I am using ubuntu 16.04.  4 cores - 6 GB RAM **
_Are the matcher server and the map server started on the same machine?_ **Yes**
_Do you use the default oberbayern.properties configuration?_ **Yes**

Thanks.

**Comment by smattheis** [comment]
Thanks for the info. The log output of the matcher server doesn't really fit to the described settings. Can you please make sure that:
1. The map server is running ("up") and listening on port 5432 ("0.0.0.0:5432->5432/tcp").
2. There is no port conflict: Please post the output of "sudo netstat -lpn | 5432".
3. Try starting the matcher server again and please post the output/error log again.

**Comment by rahimramezanian** [comment]
OK sure:
These are the steps:
```
1-


CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                      PORTS                    NAMES
1a0ac5e2ee4f        barefoot-map            "/bin/sh -c 'servi..."   31 minutes ago      Up 31 minutes               0.0.0.0:5432->5432/tcp   barefootMap


2-


                                                                List of databases
    Name    |  Owner   | Encoding  | Collate | Ctype |   Access privileges   |  Size   | Tablespace |                Description                 
------------+----------+-----------+---------+-------+-----------------------+---------+------------+--------------------------------------------
 oberbayern | postgres | SQL_ASCII | C       | C     | =Tc/postgres         +| 3495 MB | pg_default | 
            |          |           |         |       | postgres=CTc/postgres+|         |            | 
            |          |           |         |       | osmuser=CTc/postgres  |         |            | 
 postgres   | postgres | SQL_ASCII | C       | C     |                       | 6306 kB | pg_default | default administrative connection database
 template0  | postgres | SQL_ASCII | C       | C     | =c/postgres          +| 6193 kB | pg_default | unmodifiable empty database
            |          |           |         |       | postgres=CTc/postgres |         |            | 
 template1  | postgres | SQL_ASCII | C       | C     | =c/postgres          +| 6193 kB | pg_default | default template for new databases
            |          |           |         |       | postgres=CTc/postgres |         |            | 
(4 rows)


3-


$ sudo netstat -lpn | grep 5432
tcp6       0      0 :::5432                 :::*                    LISTEN      12377/docker-proxy
$ 


4-


$ java -jar target/barefoot-0.1.0-matcher-jar-with-dependencies.jar --geojson config/server.properties config/oberbayern.properties
2017-02-09 14:04:15,226 INFO  [main] ServerControl: initialize server
2017-02-09 14:04:15,266 INFO  [main] ServerControl: read database properties from file config/oberbayern.properties
2017-02-09 14:04:15,289 INFO  [main] Loader: load map from database oberbayern
2017-02-09 14:04:15,289 INFO  [main] Loader: open road reader for database oberbayern at localhost:5432
2017-02-09 14:04:15,290 INFO  [main] Loader: database.host=localhost
2017-02-09 14:04:15,290 INFO  [main] Loader: database.port=5432
2017-02-09 14:04:15,290 INFO  [main] Loader: database.name=oberbayern
2017-02-09 14:04:15,290 INFO  [main] Loader: database.table=bfmap_ways
2017-02-09 14:04:15,290 INFO  [main] Loader: database.user=osmuser
2017-02-09 14:04:15,290 INFO  [main] Loader: database.road-types=./map/tools/road-types.json
2017-02-09 14:04:15,508 INFO  [main] PostGISReader: open reader (standard)
2017-02-09 14:04:15,508 INFO  [main] PostGISReader: open reader (parameterized)
2017-02-09 14:06:23,080 ERROR [main] ServerControl: Opening PostgreSQL connection failed: The connection attempt failed.
2017-02-09 14:06:23,095 INFO  [Thread-0] ServerControl: stopping server
2017-02-09 14:06:23,095 ERROR [Thread-0] ServerControl: stopping server failed, not yet started

```

Thanks.

**Comment by smattheis** [comment]
That's pretty strange. I think we need to dig a little deeper: To make sure, the matcher can (really) connect to the map server, you need to install a little client tool and connect to the database:
1. Install a client on your host system: `sudo apt-get -y install postgresql-client`
2. Connect to the container's database: `psql -h locahost -p 5432 -d oberbayern osmuser`(enter default password: pass)
3. Check if the table exists and contains data: `select count(*) from bfmap_ways;`should return >500k

If this is all works out fine, we need to check the details of the error message:
1. Enter source directory: `cd barefoot`
2. Unzip provided patch (in the working directory): `unzip path/to/source-exception.zip`
3. Apply the provided patch: `git apply source-exception.patch`
4. Rebuild barefoot server: `mvn package -DskipTests`
5. (Make sure there is no corrupted map file: `rm oberbayern.bfmap`)
6. Restart the server with `java -jar target/barefoot-0.1.0-matcher-jar-with-dependencies.jar config/server.properties config/oberbayern.properties` and post the error log.

(Will upload patch here in a minute.)

**Comment by rahimramezanian** [comment]
Sorry for this late reply. 
In setp 2 I got the following error.

```
$ psql -h localhost -p 5432 -d oberbayern osmuser
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
Thanks. Good Weekends.

**Comment by smattheis** [comment]
This sounds very similar to what the exception of the matcher server says. It seems we get a little closer to the problem. For diagnosis reasons, please send me the output of:
``` bash
sudo docker exec -it <container> bash -c 'sudo service postgresql status'
```
``` bash
sudo docker exec -it <container> bash -c 'sudo -u postgres psql -c "select * from pg_roles;"'
```
``` bash
sudo docker exec -it <container> bash -c 'psql -h localhost -d oberbayern -U osmuser -W'
```
and the following files `postgresql.log`, `pg_hba.conf`, and `postgresql.conf` that you can extract as follows:
``` bash
sudo docker exec -it <container> bash -c 'cat /var/log/postgresql/postgresql-9.3-main.log' > postgresql.log
sudo docker exec -it <container> bash -c 'cat /etc/postgresql/9.3/main/postgresql.conf' > postgresql.conf
sudo docker exec -it <container> bash -c 'cat /etc/postgresql/9.3/main/pg_hba.conf' > pg_hba.conf
```
It would also be good to see the output of `sudo docker inspect <container>`. Thanks in advance.

I guess that the configuration of the postgresql server during image build failed. The dockerfile uses two patches to configure the postgresql server correctly, see /bmwcarit/barefoot/blob/master/map/pgsql/pg_hba.conf.patch and https://github.com/bmwcarit/barefoot/blob/master/map/pgsql/postgresql.conf.patch If these patches could for whatever reason not be applied, the postgresql server is not configured properly and is not accessible from outside the container.

**Comment by rahimramezanian** [comment]
Thank you. 
These are the outputs:

```
$ sudo docker exec -it barefoot-oberbayern bash -c 'sudo service postgresql status'
9.3/main (port 5432): online


$ sudo docker exec -it barefoot-oberbayern bash -c 'sudo -u postgres psql -c "select * from pg_roles;"'


 rolname  | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcatupdate | rolcanlogin | rolreplication | rolconnlimit | rolpassword | rolvaliduntil | rolconfig |  oid  
----------+----------+------------+---------------+-------------+--------------+-------------+----------------+--------------+-------------+---------------+-----------+-------
 postgres | t        | t          | t             | t           | t            | t           | t              |           -1 | ********    |               |           |    10
 osmuser  | f        | t          | f             | f           | f            | t           | f              |           -1 | ********    |               |           | 17791
(2 rows)



$ sudo docker exec -it barefoot-oberbayern bash -c 'psql -h localhost -d oberbayern -U osmuser -W'

Password for user osmuser: 
psql (9.3.15)
SSL connection (cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256)
Type "help" for help.

oberbayern=>
```
I ziped four files : postgresql.log, postgresql.conf, pg_hba.conf and output of inspect command (inspect.txt).

[files.zip](https://github.com/bmwcarit/barefoot/files/768396/files.zip)

Thanks.

**Comment by smattheis** [comment]
Thanks for the info. I can't see any problem in the configuration.

1. Does the error for `psql -h localhost -p 5432 -d oberbayern -U osmuser` from your host system still occur? 
2. Can you please check the version of psql with `psql --version`? I just tested to connect with psql version 9.5.5 from a ubuntu:16.04 and could successfully connect to postgresql 9.3 database.

Assuming that you have the same container running that you used with last tests and the same version of psql, you should definitely be able to login to the database with:
```
psql -h 172.17.0.3 -p 5432 -d oberbayern -U osmuser
```

If you still can't login, i have no other suggestion than trying to delete the container(s) and especially the image:
```
sudo docker rm -f <container>
sudo docker rmi barefoot-map
```
and rebuild it all, and repeat the test. Please keep me informed about it.

**Comment by rahimramezanian** [comment]
Thanks for your guide. I still have the error
```
$ psql -h localhost -p 5432 -d oberbayern -U osmuser
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
and the version is
```
$ psql --version
psql (PostgreSQL) 9.5.5
```

and I could not login to the database

```
$ psql -h 172.17.0.3 -p 5432 -d oberbayern -U osmuser
psql: could not connect to server: Connection timed out
	Is the server running on host "172.17.0.3" and accepting
	TCP/IP connections on port 5432?
```
OK I will remove and rebuild the container again. and I will post it here.
Thanks.

**Comment by smattheis** [comment]
Sorry, my bad. You should try `172.17.0.2`according to the information you provided. Of course, it should be the IP of your container.

**Comment by rahimramezanian** [comment]
Hi.

I rebuild the container again, but I am getting the same errors. Also when I make the package without skipping test
```
mvn package -e -X

Results :

Tests in error: 
  ServerTest.testServer:118->sendRequest:72 NullPointer

Tests run: 37, Failures: 0, Errors: 1, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:16 min
[INFO] Finished at: 2017-02-14T15:15:09+03:30
[INFO] Final Memory: 17M/199M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project barefoot: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/rahim/barefoot && /usr/local/java/jdk1.8.0_77/jre/bin/java -jar /home/rahim/barefoot/target/surefire/surefirebooter291619504520303315.jar /home/rahim/barefoot/target/surefire/surefire1342468510559717990tmp /home/rahim/barefoot/target/surefire/surefire_06724258432144963638tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project barefoot: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/rahim/barefoot && /usr/local/java/jdk1.8.0_77/jre/bin/java -jar /home/rahim/barefoot/target/surefire/surefirebooter291619504520303315.jar /home/rahim/barefoot/target/surefire/surefire1342468510559717990tmp /home/rahim/barefoot/target/surefire/surefire_06724258432144963638tmp
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/rahim/barefoot && /usr/local/java/jdk1.8.0_77/jre/bin/java -jar /home/rahim/barefoot/target/surefire/surefirebooter291619504520303315.jar /home/rahim/barefoot/target/surefire/surefire1342468510559717990tmp /home/rahim/barefoot/target/surefire/surefire_06724258432144963638tmp
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/rahim/barefoot && /usr/local/java/jdk1.8.0_77/jre/bin/java -jar /home/rahim/barefoot/target/surefire/surefirebooter291619504520303315.jar /home/rahim/barefoot/target/surefire/surefire1342468510559717990tmp /home/rahim/barefoot/target/surefire/surefire_06724258432144963638tmp
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:485)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:352)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:158)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:967)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:831)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:729)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```
I got the same error. Sorry The first time I just skipped the test and I did not notice that.

**Comment by smattheis** [comment]
This seems to occur because of an incompatibility between Maven Surefire and `System.exit()` calls. This won't occur if the database connection succeeds. I have created a separate issue for documentation reasons: https://github.com/bmwcarit/barefoot/issues/47

Back to your problem: I think you should test your Docker setup. You could do so by executing  the following commands on your host system:

``` bash
sudo docker run -d -p 1234:1234 ubuntu:14.04 /bin/bash -c 'while true; do echo "hello world" | netcat -l 1234; done'
```

``` bash
netcat localhost 1234
```

On each execution of the second command should see the output "hello world", until you stop the container that you created before. Does this work?

**Comment by rahimramezanian** [comment]
Thank you.
_Does this work?_ **NO**
After execution of the first command the output of the second command is NULL (no output).

**Comment by smattheis** [comment]
If this simple test fails, there is something wrong with your Docker setup. Did you update the Docker version recently? I suggest reinstalling the Docker Engine, see here: https://docs.docker.com/engine/installation/linux/ubuntu/

This functionality of Docker must work in order to get the Barefoot setup working.

**Comment by smattheis** [comment]
Seems like origin of the error is the Docker installation. Closing this issue for now.
